const actions = {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    ACCOUNTS_SAVED_FORM_NEXT_STEP: 'ACCOUNTS_SAVED_FORM_NEXT_STEP',
    SAVE_BATTLETAG: 'SAVE_BATTLETAG',
}
export default actions;