const actions = {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    ACCOUNTS_SAVED_FORM_NEXT_STEP: 'ACCOUNTS_SAVED_FORM_NEXT_STEP',
    SAVE_BATTLETAG: 'SAVE_BATTLETAG',
    SAVE_STARTING_SR: 'SAVE_STARTING_SR',
    SAVE_HEROS_FOCUSED: 'SAVE_HEROS_FOCUSED',
    SAVE_ACCOUNT: 'SAVE_ACCOUNT',
    SAVE_ACCOUNT_SUCCESS: 'SAVE_ACCOUNT_SUCCESS',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
    CREATE_USER_NODE: 'CREATE_USER_NODE',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
}
export default actions;